server:
  port: 8081
  servlet:
    session:
      timeout: 30


spring:
  datasource:
    url: jdbc:mariadb://localhost/security?characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true